In [1]:
import sys
import os
from pathlib import Path
# Go up until you find the project root
while not (Path.cwd() / ".gitignore").exists() and Path.cwd() != Path("/"):
    os.chdir("..")

In [2]:
import pandas as pd
import numpy as np

In [3]:
results_df = pd.read_csv('output/results20251026/data_integration_results_v2.csv')

In [6]:
results_df

,Unnamed: 0,region,group,TEST_PA_FRACTION,AUC_PO_only,AUC_PA_only,AUC_PO_plus_PA,AUC_PO_plus_PA_imputation,AUC_Weighted_PO_plus_PA
0,0,AWT,_plant,0.3,0.6644,0.7352,0.7431,0.7691,0.7358
1,1,AWT,_bird,0.3,0.7092,0.7472,0.7293,0.7375,0.7422
2,2,CAN,(all),0.3,0.7060,0.6794,0.7252,0.7386,0.7245
3,3,NSW,_ba,0.3,0.5797,0.6108,0.6018,0.6308,0.6371
4,4,NSW,_db,0.3,0.7781,0.6943,0.7595,0.7422,0.7846
5,5,NSW,_nb,0.3,0.6008,0.6595,0.6311,0.6591,0.6444
6,6,NSW,_ot,0.3,0.8391,0.8319,0.8843,0.8734,0.8898
7,7,NSW,_rt,0.3,0.5608,0.8245,0.8140,0.8154,0.3531
8,8,NSW,_ru,0.3,0.6805,0.8613,0.8672,0.8566,0.6228
9,9,NSW,_sr,0.3,0.8162,0.7111,0.8111,0.8037,0.8436
10,10,SA,(all),0.3,0.8092,0.7131,0.7659,0.7421,0.7284
11,11,SWI,(all),0.3,0.8671,0.8374,0.8728,0.8644,0.8746
12,12,NZ,(all),0.3,0.7635,0.7702,0.8108,0.7963,0.8085

In [4]:
AUC_cols = [x for x in results_df.columns if 'AUC' in x]
results_df.groupby(['region'])[AUC_cols].mean()

,AUC_PO_only,AUC_PA_only,AUC_PO_plus_PA,AUC_PO_plus_PA_imputation,AUC_Weighted_PO_plus_PA
region,,,,,
AWT,0.6868,0.741200,0.7362,0.753300,0.7390
CAN,0.7060,0.679400,0.7252,0.738600,0.7245
NSW,0.6936,0.741914,0.7670,0.768743,0.6822
NZ,0.7635,0.770200,0.8108,0.796300,0.8085
SA,0.8092,0.713100,0.7659,0.742100,0.7284
SWI,0.8671,0.837400,0.8728,0.864400,0.8746

In [5]:
results_df[AUC_cols].mean()

AUC_PO_only                  0.721123
AUC_PA_only                  0.744300
AUC_PO_plus_PA               0.770469
AUC_PO_plus_PA_imputation    0.771477
AUC_Weighted_PO_plus_PA      0.722262
dtype: float64